name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  test-build-full:
    name: Run tests
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Test py310
            pyversion: '3.10'
          - name: Test py311
            pyversion: '3.11'
          - name: Test py312
            pyversion: '3.12'
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Install llvmpipe and lavapipe for offscreen canvas
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install --no-install-recommends -y ffmpeg libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        cd ..
        pip install -e ".[tests]"
    - name: Test examples
      env:
        PYGFX_EXPECT_LAVAPIPE: true
      run: |
        WGPU_FORCE_OFFSCREEN=1 pytest -v tests/
